random_search:
  class: RandomizedSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 5
    n_jobs: -1
    n_iter: 20   
    random_state : 42

model_selection:
  
  model_1:
    module: sklearn.ensemble
    class: RandomForestClassifier
    params: {}
    search_param_distributions:
      max_depth: [10, 12, null, 15, 20]
      max_features: ["sqrt", "log2", null]
      n_estimators: [50, 100, 200, 300]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]

  model_2:
    module: sklearn.neighbors
    class: KNeighborsClassifier
    params: {}
    search_param_distributions:
      algorithm: ["auto", "ball_tree", "kd_tree", "brute"]
      weights: ["uniform", "distance"]
      n_neighbors: [3, 4, 5, 7, 9, 11]
      p: [1, 2]

  